### ISSUE TITLE
Sac error message 

### ISSUE THREAD

**Issue by okling** [pysmo/aimbat#105]
Hi AIMBAT and PYSMO team,

I created a new conda environment for aimbat, but I'm not able to run aimbat. Here's the error message I received when I was trying to plot my sac files downloaded using Obspy:

```
% /Users/angelling/anaconda3/envs/aimbat/bin/aimbat-sacplot -d *.HHZ       
Read configuration file: /Users/angelling/anaconda3/envs/aimbat/lib/python3.7/site-packages/pysmo/aimbat/ttdefaults.conf
Traceback (most recent call last):
  File "/Users/angelling/anaconda3/envs/aimbat/bin/aimbat-sacplot", line 8, in <module>
    sys.exit(sacplot_standalone())
  File "/Users/angelling/anaconda3/envs/aimbat/lib/python3.7/site-packages/pysmo/aimbat/plotphase.py", line 611, in sacplot_standalone
    gsac, opts = getDataOpts()
  File "/Users/angelling/anaconda3/envs/aimbat/lib/python3.7/site-packages/pysmo/aimbat/plotphase.py", line 582, in getDataOpts
    gsac = sacpkl.loadData(ifiles, opts, pppara)
  File "/Users/angelling/anaconda3/envs/aimbat/lib/python3.7/site-packages/pysmo/aimbat/sacpickle.py", line 500, in loadData
    isac = SacIO.from_file(ifile0)
  File "/Users/angelling/anaconda3/envs/aimbat/lib/python3.7/site-packages/pysmo/core/sac/sacio.py", line 305, in from_file
    newinstance.read(filename)
  File "/Users/angelling/anaconda3/envs/aimbat/lib/python3.7/site-packages/pysmo/core/sac/sacio.py", line 270, in read
    setattr(self, header_field, value)
  File "/Users/angelling/anaconda3/envs/aimbat/lib/python3.7/site-packages/pysmo/core/sac/sacheader.py", line 237, in __set__
    raise ValueError('%s not a valid value for %s' % (value, self.name))
ValueError: 9 not a valid value for iztype
```

Looks like it's related to the sac attribute, but I can't figure out why. Any ideas on this? Thanks in advance!

**Versions**:
Python version: 3.7.10
Obspy: 1.2.2
pyqtgraph: 0.12.1
pyyaml: 5.4.1
pysmo-aimbat: 1.0.5 (via pip)
Operating System name/version: macOS Catalina

**Comment by smlloyd** [comment]
This was actually a bug in pysmo. Fixed here: 81075bf3ecaa8fc05a3c56b64d3b4273b3cb3ca9
