### ISSUE TITLE
Issues usign pkl to sac files convert

### ISSUE THREAD

**Issue by gposada** [pysmo/aimbat#97]
Hello AIMBAT and PYSMO team,

I hope you are safe.

I have some problems when I try to convert my final pkl to sac files using the command: aimbat-sac2pkl --p2s sac.pkl. 

The error in the code shown: 

aimbat-sac2pkl --p2s sac.pkl
File conversion: pkl --> sac
Traceback (most recent call last):
  File "/home/gustavo/.local/bin/aimbat-sac2pkl", line 8, in <module>
    sys.exit(main())
  File "/home/gustavo/.local/lib/python3.8/site-packages/pysmo/aimbat/sacpickle.py", line 600, in main
    pkl2sac(pkfile, zipmode)
  File "/home/gustavo/.local/lib/python3.8/site-packages/pysmo/aimbat/sacpickle.py", line 333, in pkl2sac
    obj2sac(gsac)
  File "/home/gustavo/.local/lib/python3.8/site-packages/pysmo/aimbat/sacpickle.py", line 305, in obj2sac
    sacdh.savesac()
  File "/home/gustavo/.local/lib/python3.8/site-packages/pysmo/aimbat/sacpickle.py", line 224, in savesac
    self.sethdrs(sacobj)
  File "/home/gustavo/.local/lib/python3.8/site-packages/pysmo/aimbat/sacpickle.py", line 201, in sethdrs
    setattr(sacobj, 'kuser'+str(i), kusers[i])
  File "/home/gustavo/.local/lib/python3.8/site-packages/pysmo/core/sac/sacheader.py", line 278, in __set__
    raise ValueError('%s is too long - maximum length is %s' % \
ValueError: b'False   ' is too long - maximum length is 8

Are there some ways to solve these problems?

thanks.

**Comment by smlloyd** [comment]
Fixed in pysmo version 0.8.3
